server.port: 8761
spring.application.name: spring-cloud-eureka-server

eureka:
  instance:
    hostname: localhost
  client:
    registerWithEureka: false
    fetchRegistry: false
    serviceUrl:
      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/

# Ribbon load-balancer is now in maintenance mode, disabling Ribbon with Eureka Server and Client starters,
# using the Spring Cloud LoadBalancer
spring.cloud.loadbalancer.ribbon.enabled: false
