server:
  port: 8761

spring:
  application:
    name: spring-cloud-eureka-server

logging:
  level:
    com.spring.cloud: debug

management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: ALWAYS
  metrics:
    tags:
      application: ${spring.application.name}
