#spring.profiles.active: commons

server.port: 8800

spring.cloud.nacos.discovery.server-addr: 127.0.0.1:8848

# LOGGING
logging.level.com.spring.cloud: DEBUG
logging.pattern.console: ${CONSOLE_LOG_PATTERN:-%clr(%d{yyyy-MM-dd HH:mm:ss.SSS}){faint} %clr(${LOG_LEVEL_PATTERN:-%5p}) %clr(${PID:- }){magenta} %clr(---){faint} %clr([%15.15t]){faint} %clr(%-40.40logger{39}){cyan} %4line %clr(:){faint} %m%n${LOG_EXCEPTION_CONVERSION_WORD:-%wEx}}

# 发现客户端注册之后，Eureka默认认为是可用状态，不再检查发现客户端是否可用，开启发现客户端心跳检查，将发现客户端状态定时发送给Eureka
eureka.client.healthcheck.enabled: true

skywalking.agent.service_name: spring-cloud-sleuth-skywalking1
skywalking.collector.backend_service: localhost:11800

