server.port: 8900
spring.application.name: spring-cloud-stream-kafka-producer

#eureka.client.serviceUrl.defaultZone: http://localhost:8761/eureka/

# Kafka Binder Properties
spring.cloud.stream.kafka.binder.brokers: 192.168.31.131:9092
# 自动创建topic
spring.cloud.stream.kafka.binder.autoCreateTopics: true
# 自动增加分区
spring.cloud.stream.kafka.binder.autoAddPartitions: true

# Producer Binding Properties
# topic分区数量
spring.cloud.stream.bindings.topic.producer.partitionCount: 3
