#spring.profiles.active: commons

spring.application.name: spring-cloud-circuit-breaker-resilience4j2
server.port: 8810

eureka.client.serviceUrl.defaultZone: http://localhost:8761/eureka/

# LOGGING
logging.level.com.spring.cloud: DEBUG

management.endpoints.web.exposure.include: "*"

spring.cloud.circuitbreaker.resilience4j.enabled: true
