logging.level.com.spring.cloud: DEBUG

server:
  port: 8762

spring:
  application:
    name: spring-cloud-admin-server
  boot:
    admin:
      context-path: "/admin"

eureka:
  instance:
    hostname: localhost
    leaseRenewalIntervalInSeconds: 10
    health-check-url-path: /actuator/health
    metadata-map:
      startup: ${random.int}    # needed to trigger info and endpoint update after restart
  client:
    registerWithEureka: false
    fetchRegistry: true
    registryFetchIntervalSeconds: 5
    healthcheck:
      enabled: true
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/

management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: ALWAYS
    shutdown:
      enabled: true
  metrics:
    tags:
      application: ${spring.application.name}

# spring boot admin ui login user & password
spring.security.user.name: "user"
spring.security.user.password: "password"
