FROM openjdk:17.0.2 as builder
WORKDIR .
ARG JAR_FILE=target/*.jar
COPY ${JAR_FILE} application.jar
RUN java -Djarmode=layertools -jar application.jar extract

FROM openjdk:17.0.2
WORKDIR .
COPY --from=builder ./dependencies/ ./
COPY --from=builder ./spring-boot-loader/ ./
COPY --from=builder ./snapshot-dependencies/ ./
COPY --from=builder ./application/ ./
# 安装Arthas
COPY --from=hengyunabc/arthas:3.6.2 /opt/arthas /opt/arthas
ENTRYPOINT ["java", "org.springframework.boot.loader.JarLauncher"]
