server.port: 8880

spring.cloud.nacos.discovery.server-addr: 127.0.0.1:8848

# find Zipkin through service discovery
spring.zipkin.baseUrl: http://localhost:9411/

# LOGGING
# Instead of logging the request in the handler explicitly, you could set
#logging.level.org.springframework.web.servlet.DispatcherServlet: DEBUG
logging.level.com.spring.cloud: DEBUG
logging.pattern.console: ${CONSOLE_LOG_PATTERN:-%clr(%d{yyyy-MM-dd HH:mm:ss.SSS}){faint} %clr(${LOG_LEVEL_PATTERN:-%5p}) %clr(${PID:- }){magenta} %clr(---){faint} %clr([%15.15t]){faint} %clr(%-40.40logger{39}){cyan} %4line %clr(:){faint} %m%n${LOG_EXCEPTION_CONVERSION_WORD:-%wEx}}

