server.port: 8891
spring.application.name: spring-cloud-stream-kafka-consumer

#eureka.client.serviceUrl.defaultZone: http://localhost:8761/eureka/

# Kafka Binder Properties
spring.cloud.stream.kafka.binder.brokers: 192.168.31.131:9092

## Common Binding Properties
# 定义channel(topic)的消费者组 channel name: topic
spring.cloud.stream.bindings.topic.group: spring-cloud-stream-kafka-consumer

## Consumer Binding Properties
spring.cloud.stream.bindings.topic.consumer.instanceCount: 5
spring.cloud.stream.bindings.topic.consumer.instanceIndex: 0

# 注：
# 消费者实例数量大于topic分区数量时，部分消费者实例不能接收消息
# 消费者实例数量等于topic分区数量时，每个消费者实例都能接收消息
# 消费者实例数量小于topic分区数量时，部分消费者实例接收多个分区的消息
