spring:
  main:
    allow-bean-definition-overriding: true
  application:
    name: spring-cloud-soul-microservice1
#   cloud:
#    nacos:
#       discovery:
#          server-addr: 127.0.0.1:8848

server:
  port: 8081
  address: 0.0.0.0

management:
  health:
    defaults:
      enabled: false

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/ #your eureka address
  instance:
    prefer-ip-address: true

soul:
  client:
    registerType: http #http #zookeeper #etcd
    serverLists: http://localhost:9095 #http://localhost:9095 #localhost:2181 #http://localhost:2379
    props:
      contextPath: /microservice1

springCloud-test:
  ribbon.NFLoadBalancerRuleClassName: com.netflix.loadbalancer.RandomRule




