kind: Deployment
apiVersion: apps/v1
metadata:
  name: user-service
  namespace: default
  labels:
    app: user-service
  annotations:
    deployment.kubernetes.io/revision: '4'
    kubesphere.io/creator: admin
spec:
  replicas: 1
  selector:
    matchLabels:
      app: user-service
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: user-service
      annotations:
        kubesphere.io/restartedAt: '2022-07-08T06:15:09.818Z'
    spec:
      volumes:
        - name: config
          configMap:
            name: user-config
            items:
              - key: application.yml
                path: application.yml
              - key: application-common.yml
                path: application-common.yml
              - key: application-dev.yml
                path: application-dev.yml
              - key: application-k8s.yml
                path: application-k8s.yml
            defaultMode: 420
      containers:
        - name: container-hrdy9f
          image: 'limengcanyu/spring-cloud-user-service:0.0.1-SNAPSHOT'
          ports:
            - name: http-8083
              containerPort: 8083
              protocol: TCP
          env:
            - name: JAVA_TOOL_OPTIONS
              value: '-Dspring.profiles.active=common,k8s'
          resources:
            limits:
              cpu: 500m
              memory: 200Mi
          volumeMounts:
            - name: config
              readOnly: true
              mountPath: /config
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
          imagePullPolicy: IfNotPresent
      restartPolicy: Always
      terminationGracePeriodSeconds: 30
      dnsPolicy: ClusterFirst
      serviceAccountName: default
      serviceAccount: default
      securityContext: {}
      schedulerName: default-scheduler
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 25%
      maxSurge: 25%
  revisionHistoryLimit: 10
  progressDeadlineSeconds: 600
