logging:
  pattern:
    console: "${CONSOLE_LOG_PATTERN:-%clr(%d{${LOG_DATEFORMAT_PATTERN:-yyyy-MM-dd HH:mm:ss.SSS}}){faint} %clr(${LOG_LEVEL_PATTERN:-%5p}) %clr(${PID:- }){magenta} %clr(---){faint} %clr([%15.15t]){faint} %clr(%-40.40logger{39}){cyan} %line %clr(:){faint} %m%n${LOG_EXCEPTION_CONVERSION_WORD:-%wEx}}"
    file: "${FILE_LOG_PATTERN:-%d{${LOG_DATEFORMAT_PATTERN:-yyyy-MM-dd HH:mm:ss.SSS}} ${LOG_LEVEL_PATTERN:-%5p} ${PID:- } --- [%t] %-40.40logger{39} : %m%n${LOG_EXCEPTION_CONVERSION_WORD:-%wEx}}"
  level:
    com.spring.cloud: DEBUG

management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: ALWAYS
    shutdown:
      enabled: true
  metrics:
    tags:
      application: ${spring.application.name}

spring:
  cloud:
    openfeign:
      client:
        config:
          default: # 对所有服务的feign调用有效
            connectTimeout: 5000
            readTimeout: 5000
            loggerLevel: basic
            requestInterceptors:
              - com.spring.cloud.common.interceptor.FeignRequestInterceptor
#          spring-cloud-order-service: # 针对特定服务的feign调用有效
#            requestInterceptors:
#              - com.spring.cloud.common.interceptor.FeignRequestInterceptor

tlog:
  enable-invoke-time-print: true
  pattern: "[$preApp][$preIp][$traceId][$spanId]"
