# 不能作为公共配置，会报错

logging:
  level:
    io.seata: debug

seata:
  tx-service-group: default_tx_group # 事务分组配置（在v1.5之后默认值为default_tx_group）
  service:
    vgroup-mapping:
      default_tx_group: default # 指定事务分组至集群映射关系（冒号右侧的集群名需要与Seata-server注册到Nacos的cluster保持一致）
  registry:
    # 通过Nacos获取seata-server服务信息
    type: nacos # 使用nacos作为注册中心
    nacos:
      server-addr: 127.0.0.1:8848 # nacos注册中心IP:端口
      application: seata-server # Seata服务名（应与seata-server实际注册的服务名一致）
      group: SEATA_GROUP # Seata分组名（应与seata-server实际注册的分组名一致）
